name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      with:
          access_key_id: ${{ access_key_id }}
          secret_key_id: ${{ secret_key_id }}

      - name: Run a one-line script
        run: sudo sed -i 's/^access_key_id/${{ access_key_id }}' index.js
  
