name: replace

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
 
env:
  DAY_OF_WEEK: Monday 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      access_key: AKIA2YWRVRZFMNWRUTG7
    steps:
      - uses: actions/checkout@v3
  
      - name: Run a one-line script
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo $access_key
        
      - name: Run a one-line script
        run: sed -i 's/"access_key_id"/${{ secrets.ACCESSKEYID }}/g' index.js
