name: replace

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sed -i 's/accessKeyId: "access_key_id"/accessKeyId: "${{ access_key_id }}"/g' index.js
  
